# Generated by Django 5.2.15 on 2026-07-02 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("outpass_app", "0010_alter_outpass_request_request_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Machine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("machine_name", models.CharField(max_length=100)),
                ("ip_address", models.GenericIPAddressField()),
                ("port", models.IntegerField(default=4370)),
                (
                    "serial_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ONLINE", "Online"),
                            ("OFFLINE", "Offline"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=20,
                    ),
                ),
                ("last_connected", models.DateTimeField(blank=True, null=True)),
                (
                    "last_attendance_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of the last synced attendance log from this machine",
                        null=True,
                    ),
                ),
                (
                    "connection_timeout",
                    models.IntegerField(
                        default=5, help_text="Connection timeout in seconds"
                    ),
                ),
                (
                    "polling_interval",
                    models.IntegerField(
                        default=60, help_text="Sync interval in seconds"
                    ),
                ),
                (
                    "auto_sync_enabled",
                    models.BooleanField(
                        default=True, help_text="True if automated sync is enabled"
                    ),
                ),
                (
                    "machine_enabled",
                    models.BooleanField(
                        default=True, help_text="True if this machine is active"
                    ),
                ),
                (
                    "last_successful_sync",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of the last successful synchronization",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="BiometricUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "machine_uid",
                    models.IntegerField(
                        help_text="UID index assigned by the biometric device"
                    ),
                ),
                (
                    "user_id",
                    models.CharField(
                        help_text="User ID string defined on the biometric device",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("card_number", models.CharField(blank=True, max_length=50, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("last_sync", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        db_column="student_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="biometric_users",
                        to="outpass_app.student_master",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AttendanceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "machine_uid",
                    models.IntegerField(
                        blank=True, help_text="Raw machine UID", null=True
                    ),
                ),
                (
                    "verify_type",
                    models.IntegerField(
                        help_text="Verification mode (e.g. fingerprint, face, card, password)"
                    ),
                ),
                ("attendance_time", models.DateTimeField()),
                (
                    "processed",
                    models.BooleanField(
                        default=False,
                        help_text="True if successfully processed against the verification queue",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        db_column="student_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendance_logs",
                        to="outpass_app.student_master",
                    ),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_logs",
                        to="biometric.machine",
                    ),
                ),
            ],
            options={
                "ordering": ["-attendance_time"],
                "unique_together": {("machine", "machine_uid", "attendance_time")},
            },
        ),
        migrations.CreateModel(
            name="PendingBiometricVerification",
            fields=[
                (
                    "request",
                    models.OneToOneField(
                        db_column="request_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="biometric_verification",
                        serialize=False,
                        to="outpass_app.outpass_request",
                    ),
                ),
                ("approved_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField()),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("WAITING", "Waiting"),
                            ("ACCEPTED", "Accepted"),
                            ("TIME_OUT", "Timed Out"),
                            ("FAILED", "Failed"),
                        ],
                        default="WAITING",
                        max_length=20,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "timed_out_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the request timed out",
                        null=True,
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "attendance_log",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verifications",
                        to="biometric.attendancelog",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        db_column="student_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="biometric_verifications",
                        to="outpass_app.student_master",
                    ),
                ),
            ],
            options={
                "ordering": ["approved_at"],
            },
        ),
        migrations.CreateModel(
            name="SyncHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sync_type",
                    models.CharField(
                        choices=[
                            ("USERS", "Users Sync"),
                            ("LOGS", "Attendance Logs Sync"),
                        ],
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("total_records", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[("SUCCESS", "Success"), ("FAILED", "Failed")],
                        max_length=20,
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_histories",
                        to="biometric.machine",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
    ]
