# Generated by Django 5.2.15 on 2026-07-02 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("biometric", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pendingbiometricverification",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("WAITING", "Waiting"),
                    ("ACCEPTED", "Accepted"),
                    ("TIME_OUT", "Timed Out"),
                    ("FAILED", "Failed"),
                    ("OUT", "OUT"),
                    ("READY_FOR_IN", "READY_FOR_IN"),
                ],
                default="WAITING",
                max_length=20,
            ),
        ),
    ]
