# Generated by Django 5.2.15 on 2026-06-30 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_master',
            fields=[
                ('student_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=150)),
                ('mobile_no', models.CharField(max_length=15)),
                ('department', models.CharField(max_length=150)),
                ('course', models.CharField(max_length=150)),
                ('semester', models.IntegerField()),
                ('hostel_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='student_profiles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'student_master',
            },
        ),
        migrations.CreateModel(
            name='system_user',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact', models.CharField(max_length=15)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='user_profiles/')),
                ('user_name', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=150)),
                ('hostel_name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'system_user',
            },
        ),
        migrations.CreateModel(
            name='outpass_request',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('requested_exit_datetime', models.DateTimeField()),
                ('actual_exit_datetime', models.DateTimeField(blank=True, null=True)),
                ('requested_entry_datetime', models.DateTimeField()),
                ('actual_entry_datetime', models.DateTimeField(blank=True, null=True)),
                ('outing_reason', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('note', models.TextField(blank=True, null=True)),
                ('request_status', models.CharField(choices=[('Initiate', 'Initiate'), ('Approved', 'Approved'), ('Accept', 'Accept'), ('Decline', 'Decline'), ('Reject', 'Reject'), ('OUT', 'OUT'), ('IN', 'IN'), ('Time out', 'Time out')], default='Initiate', max_length=50)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.CharField(max_length=100)),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('student_id', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='outpass_app.student_master')),
            ],
            options={
                'db_table': 'outpass_request',
            },
        ),
    ]
