# Generated by Django 5.2.15 on 2026-06-30 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outpass_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='system_user',
            name='gate_name',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
