# Generated by Django 5.2.15 on 2026-07-01 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outpass_app', '0002_system_user_gate_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='outpass_request',
            name='early_grace',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='outpass_request',
            name='late_grace',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='outpass_request',
            name='request_status',
            field=models.CharField(choices=[('Initiate', 'Initiate'), ('Approved', 'Approved'), ('Accept', 'Accept'), ('Decline', 'Decline'), ('Reject', 'Reject'), ('OUT', 'OUT'), ('IN', 'IN'), ('Time out', 'Time out')], db_index=True, default='Initiate', max_length=50),
        ),
        migrations.AlterField(
            model_name='outpass_request',
            name='requested_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='student_master',
            name='student_name',
            field=models.CharField(db_index=True, max_length=150),
        ),
    ]
