# Generated by Django 5.2.15 on 2026-07-01 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outpass_app', '0003_outpass_request_early_grace_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_master',
            name='hostel_name',
            field=models.CharField(choices=[('Hostel A', 'Hostel A'), ('Hostel B', 'Hostel B'), ('Hostel C', 'Hostel C'), ('Hostel D', 'Hostel D'), ('Hostel E', 'Hostel E')], max_length=100),
        ),
    ]
