# Generated by Django 5.2.15 on 2026-07-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outpass_app', '0004_alter_student_master_hostel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outpass_request',
            name='outing_reason',
            field=models.CharField(choices=[('Medical', 'Medical'), ('Personal', 'Personal'), ('Education leave', 'Education leave'), ('Sunday Outing', 'Sunday Outing'), ('Semester Break', 'Semester Break'), ('Emergency', 'Emergency')], max_length=255),
        ),
    ]
