# Generated by Django 5.2.15 on 2026-07-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outpass_app', '0005_alter_outpass_request_outing_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='system_user',
            name='is_first_login',
            field=models.BooleanField(default=True),
        ),
    ]
