# Generated by Django 5.2.15 on 2026-07-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outpass_app", "0006_system_user_is_first_login"),
    ]

    operations = [
        migrations.AddField(
            model_name="system_user",
            name="allowed_purposes",
            field=models.CharField(default="Emergency,Sunday Outing", max_length=255),
        ),
    ]
