# Generated by Django 5.2.15 on 2026-07-01 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outpass_app", "0007_system_user_allowed_purposes"),
    ]

    operations = [
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=50, unique=True)),
                ("can_view_students", models.BooleanField(default=True)),
                ("can_view_details", models.BooleanField(default=True)),
                ("can_approve", models.BooleanField(default=True)),
                ("can_mark_out", models.BooleanField(default=True)),
                ("can_mark_in", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "role_permission",
            },
        ),
    ]
