# Generated by Django 5.2.15 on 2026-07-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outpass_app", "0008_rolepermission"),
    ]

    operations = [
        migrations.AddField(
            model_name="rolepermission",
            name="allowed_purposes",
            field=models.CharField(default="All", max_length=255),
        ),
    ]
