# Generated by Django 5.2.15 on 2026-07-02 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outpass_app", "0009_rolepermission_allowed_purposes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outpass_request",
            name="request_status",
            field=models.CharField(
                choices=[
                    ("Initiate", "Initiate"),
                    ("Approved", "Approved"),
                    ("ACCEPTED", "ACCEPTED"),
                    ("Accept", "Accept"),
                    ("Decline", "Decline"),
                    ("Reject", "Reject"),
                    ("OUT", "OUT"),
                    ("IN", "IN"),
                    ("TIME_OUT", "TIME_OUT"),
                    ("Time out", "Time out"),
                ],
                db_index=True,
                default="Initiate",
                max_length=50,
            ),
        ),
    ]
