# Generated by Django 5.2.15 on 2026-07-04 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outpass_app", "0010_alter_outpass_request_request_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="outpass_request",
            name="status_changed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
