# Generated by Django 5.2.15 on 2026-07-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outpass_app", "0011_outpass_request_status_changed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="outpass_request",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="outpass_request",
            name="declined_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
