# Generated by Django 5.2.15 on 2026-07-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outpass_app", "0012_outpass_request_approved_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="outpass_request",
            name="leave_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="outpass_request",
            name="parent_confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
