# Generated by Django 5.2.15 on 2026-07-07 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("outpass_app", "0013_outpass_request_leave_reason_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="outpass_request",
            old_name="status_changed_at",
            new_name="terminated_at",
        ),
    ]
