# Generated by Django 5.2.15 on 2026-07-07 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outpass_app", "0014_rename_status_changed_at_outpass_request_terminated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="outpass_request",
            name="recovery_attempts",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="outpass_request",
            name="recovery_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="outpass_request",
            name="request_status",
            field=models.CharField(
                choices=[
                    ("Initiate", "Initiate"),
                    ("Approved", "Approved"),
                    ("ACCEPTED", "ACCEPTED"),
                    ("Accept", "Accept"),
                    ("Decline", "Decline"),
                    ("Reject", "Reject"),
                    ("OUT", "OUT"),
                    ("IN", "IN"),
                    ("TIME_OUT", "TIME_OUT"),
                    ("Time out", "Time out"),
                    ("TERMINATED", "TERMINATED"),
                ],
                db_index=True,
                default="Initiate",
                max_length=50,
            ),
        ),
    ]
