# Generated by Django 5.2.15 on 2026-07-08 07:12

from django.db import migrations, models


def migrate_terminated_to_timeout(apps, schema_editor):
    outpass_request = apps.get_model('outpass_app', 'outpass_request')
    outpass_request.objects.filter(request_status='TERMINATED').update(request_status='TIME OUT')


class Migration(migrations.Migration):

    dependencies = [
        ("outpass_app", "0015_outpass_request_recovery_attempts_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate_terminated_to_timeout),
        migrations.AlterField(
            model_name="outpass_request",
            name="request_status",
            field=models.CharField(
                choices=[
                    ("Initiate", "Initiate"),
                    ("Approved", "Approved"),
                    ("ACCEPTED", "ACCEPTED"),
                    ("Accept", "Accept"),
                    ("Decline", "Decline"),
                    ("Reject", "Reject"),
                    ("OUT", "OUT"),
                    ("IN", "IN"),
                    ("TIME_OUT", "TIME_OUT"),
                    ("Time out", "Time out"),
                    ("TIME OUT", "TIME OUT"),
                ],
                db_index=True,
                default="Initiate",
                max_length=50,
            ),
        ),
    ]
